"use client";

import { useRouter } from "next/navigation";
import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
export default function HomePage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-gradient-to-br from-black via-[#0a0014] to-[#12002b] text-white flex flex-col">

      {/* TOP BAR WITH LOGIN */}
      <header className="w-full flex items-center justify-between px-6 py-4 border-b border-white/10">
        <div className="flex items-center gap-3">
          {/* FOX MASCOT (placeholder emoji or replace with image) */}
          <div className="text-3xl">🦊</div>
          <span className="text-xl font-semibold tracking-wide">PyLynx</span>
        </div>

        <button
          onClick={() => router.push("/login")}
          className="px-4 py-2 bg-zinc-800 hover:bg-zinc-700 rounded-lg text-sm font-medium transition"
        >
          Log In
        </button>
      </header>

      {/* SECTION 1 — Get Started */}
      <section className="flex flex-col items-center justify-center flex-1 p-10 border-b border-white/10">
        <h2 className="text-4xl font-bold mb-4 tracking-wide">
          Get Started
        </h2>

        <p className="text-zinc-400 max-w-xl text-center mb-8">
          Boot into the PyLynx OS demo and experience the fox‑core boot chain,
          mythic desktop environment, and youth‑powered app system.  
          Built for exploration. Designed for remixing.
        </p>

        <button
          onClick={() => router.push("/demo")}
          className="
            px-8 py-3 rounded-xl text-lg font-semibold
            bg-purple-600 hover:bg-purple-700
            shadow-[0_0_20px_rgba(128,0,255,0.4)]
            transition-all
          "
        >
          Launch Demo
        </button>
      </section>

      {/* SECTION 2 — For Youth Remixers */}
      <section className="flex flex-col items-center justify-center flex-1 p-10">
        <h2 className="text-4xl font-bold mb-4 tracking-wide">
          For Youth Remixers
        </h2>

        <p className="text-zinc-400 max-w-xl text-center">
          PyLynx is built to be hacked, remixed, and reshaped.  
          Dive into the source code, customize the UI, rewrite the bootloader,
          or build your own apps.  
          Every part of PyLynx is designed to be teachable and remixable.
        </p>
      </section>

    </div>
  );
}
